<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup Condition="Exists('GoogleOAuthClient.local.xml')">
    <EmbeddedResource Include="GoogleOAuthClient.local.xml" LogicalName="Halill.GoogleOAuthClient.xml" />
  </ItemGroup>
</Project>
